#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEFAULT_BRIDGE_ENV="$ROOT/runtime.env"
if [[ ! -f "$DEFAULT_BRIDGE_ENV" && -f "$ROOT/.env" ]]; then
  DEFAULT_BRIDGE_ENV="$ROOT/.env"
fi
BRIDGE_ENV="${DIANA_BRIDGE_ENV:-$DEFAULT_BRIDGE_ENV}"

load_bridge_env() {
  local line key value

  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%$'\r'}"
    [[ "$line" =~ ^[[:space:]]*$ ]] && continue
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ "$line" =~ ^[[:space:]]*(export[[:space:]]+)?([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]] || continue

    key="${BASH_REMATCH[2]}"
    value="${BASH_REMATCH[3]}"
    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%"${value##*[![:space:]]}"}"
    if [[ "$value" == \"*\" && "$value" == *\" ]]; then
      value="${value:1:${#value}-2}"
    elif [[ "$value" == \'*\' && "$value" == *\' ]]; then
      value="${value:1:${#value}-2}"
    fi

    case "$key" in
      DIANA_TTS_FFMPEG_PATH|DIANA_TTS_SILK_ENCODER_PATH|DIANA_TTS_SILK_BITRATE)
        export "$key=$value"
        ;;
      DIANA_WEB_SEARCH_CONFIG_FILE|DIANA_WEB_SEARCH_CONFIGS|EXA_API_KEY|EXA_API_KEY_*|TAVILY_API_KEY|TAVILY_API_KEY_*|DIANA_WEB_SEARCH_KEY_*)
        export "$key=$value"
        ;;
      ADMIN_TOKEN|AGENT_MCP_CONFIG|AGENT_WORK_DIR|APP_DB_PATH|BILI_SESSDATA|BOT_QQ|DIANA_ADMIN_AUTH_CONFIG_FILE|DIANA_ADMIN_LOGIN_PATH|DIANA_ADMIN_TOKEN|DIANA_AGENT_ENABLED|DIANA_AGENT_MCP_CONFIG|DIANA_AGENT_SKILL_ROOTS|DIANA_AGENT_WORK_DIR|DIANA_API_KEY|DIANA_API_KEY_FILE|DIANA_APP_EXECUTABLE|DIANA_BASE_URL|DIANA_BILI_SESSDATA|DIANA_DOUYIN_CK|DIANA_GROUP_TRIGGERS|DIANA_HEADLESS_BROWSER_EXECUTABLE|DIANA_HEADLESS_BROWSER_MAX_CHARS|DIANA_HEADLESS_BROWSER_TIMEOUT_MS|DIANA_HEADLESS_BROWSER_VIRTUAL_TIME_MS|DIANA_LLM_QQ_ID_MASKING_ENABLED|DIANA_MACOS_PDF_HELPER|DIANA_MODEL|DIANA_OCR_CACHE_DIR|DIANA_OCR_CACHE_VERSION|DIANA_OCR_CONCURRENCY|DIANA_OCR_FINAL_CONTEXT_CHARS|DIANA_OCR_JPEG_QUALITY|DIANA_OCR_MAX_IMAGE_MB|DIANA_OCR_MAX_PAGES_PER_FILE|DIANA_OCR_REDUCE_CHUNK_CHARS|DIANA_OCR_RENDER_CONCURRENCY|DIANA_OCR_RENDER_DPI|DIANA_OCR_TASK_TIMEOUT_MINUTES|DIANA_OWNER_ID|DIANA_PASSIVE_REPLY_CHANCE|DIANA_PASSIVE_REPLY_PROMPT|DIANA_PASSIVE_REPLY_ROUTER_PROMPT|DIANA_PASSIVE_REPLY_THRESHOLD|DIANA_QQ_APP|DIANA_QQ_ENFORCE_APP|DIANA_QQ_EXPECTED_VERSION|DIANA_RESOLVER_PROXY|DIANA_RESOLVER_VIDEO_MAX_DURATION|DIANA_RESOLVER_VIDEO_MAX_MB|DIANA_START_NAPCAT|DIANA_TTS_API_KEY|DIANA_TTS_ENDPOINT|DIANA_TTS_MAX_CHARS|DIANA_TTS_OUTPUT_DIR|DIANA_TTS_PROMPT_LANG|DIANA_TTS_PROMPT_TEXT|DIANA_TTS_REF_AUDIO_PATH|DIANA_TTS_SPEED_FACTOR|DIANA_TTS_TEXT_LANG|DIANA_TTS_TIMEOUT_SECONDS|DIANA_TTS_VOICE_NAME|DIANA_XHS_CK|DIANA_YTDLP_COOKIES|DIANA_YTDLP_COOKIES_FROM_BROWSER|DOUYIN_CK|FRONTEND_DIST|HOST|LLM_API_FORMAT|LLM_API_KEY|LLM_API_KEY_FILE|LLM_BASE_URL|LLM_CONTEXT_WINDOW_TOKENS|LLM_IMAGE_BASE_URL|LLM_IMAGE_MODEL|LLM_IMAGE_ORIGIN|LLM_IMAGE_TIMEOUT_MS|LLM_MAX_CONTEXT_TOKENS|LLM_MAX_OUTPUT_TOKENS|LLM_MODEL|LLM_PROVIDER|LLM_REASONING_EFFORT|LLM_TEMPERATURE|LLM_TIMEOUT_MS|LLM_USER_AGENT|LOG_PATH|NAPCAT_QQ|ONEBOT_ACCESS_TOKEN|ONEBOT_REVERSE_WS_ENDPOINT|PORT|QQBOT_ENABLED|QQBOT_GROUP_TEST_ENABLED|QQBOT_ONEBOT_ACCESS_TOKEN|QQBOT_OWNER_ID|QQBOT_QQ|QQBOT_SELF_ID|RESOLVER_PROXY|XHS_CK)
        export "$key=$value"
        ;;
    esac
  done < "$1"
}

if [[ -f "$BRIDGE_ENV" ]]; then
  load_bridge_env "$BRIDGE_ENV"
fi

mkdir -p "$ROOT/data" "$ROOT/logs"

if [[ "$(uname -s)" == "Darwin" && "${DIANA_START_NAPCAT:-true}" != "false" ]]; then
  NAPCAT_LAUNCHER="$ROOT/scripts/start-napcat-mac.sh"
  if [[ -x "$NAPCAT_LAUNCHER" ]]; then
    if ! "$NAPCAT_LAUNCHER" >>"$ROOT/logs/napcat-launch.log" 2>&1; then
      echo "NapCat auto-start failed; see $ROOT/logs/napcat-launch.log" >&2
    fi
  fi
fi

export HOST="${HOST:-127.0.0.1}"
export PORT="${PORT:-18080}"
export APP_DB_PATH="${APP_DB_PATH:-$ROOT/data/diana-qq-bot.db}"
export LOG_PATH="${LOG_PATH:-$ROOT/logs/diana-qq-bot.log}"
export FRONTEND_DIST="${FRONTEND_DIST:-$ROOT/frontend/dist}"

export QQBOT_ENABLED="${QQBOT_ENABLED:-true}"
export QQBOT_GROUP_TEST_ENABLED="${QQBOT_GROUP_TEST_ENABLED:-true}"
export DIANA_AGENT_ENABLED="${DIANA_AGENT_ENABLED:-true}"
export DIANA_AGENT_WORK_DIR="${DIANA_AGENT_WORK_DIR:-${AGENT_WORK_DIR:-$ROOT}}"
export DIANA_AGENT_SKILL_ROOTS="${DIANA_AGENT_SKILL_ROOTS:-$ROOT/skills}"
export DIANA_AGENT_MCP_CONFIG="${DIANA_AGENT_MCP_CONFIG:-${AGENT_MCP_CONFIG:-$ROOT/.mcp.json}}"
export ONEBOT_REVERSE_WS_ENDPOINT="${ONEBOT_REVERSE_WS_ENDPOINT:-ws://127.0.0.1:${PORT}/onebot/v11/ws}"
export ONEBOT_ACCESS_TOKEN="${ONEBOT_ACCESS_TOKEN:-${QQBOT_ONEBOT_ACCESS_TOKEN:-}}"
export DIANA_OWNER_ID="${DIANA_OWNER_ID:-${QQBOT_OWNER_ID:-}}"
export DIANA_GROUP_TRIGGERS="${DIANA_GROUP_TRIGGERS:-Diana,diana}"

if [[ -z "${QQBOT_QQ:-}" ]]; then
  export QQBOT_QQ="${QQBOT_SELF_ID:-${BOT_QQ:-${NAPCAT_QQ:-}}}"
fi

export LLM_PROVIDER="${LLM_PROVIDER:-openai_compatible}"
if [[ -z "${LLM_BASE_URL:-}" && -n "${DIANA_BASE_URL:-}" ]]; then
  export LLM_BASE_URL="$DIANA_BASE_URL"
fi
if [[ -z "${LLM_MODEL:-}" && -n "${DIANA_MODEL:-}" ]]; then
  export LLM_MODEL="$DIANA_MODEL"
fi
if [[ -z "${LLM_API_KEY:-}" ]]; then
  if [[ -n "${DIANA_API_KEY:-}" ]]; then
    export LLM_API_KEY="$DIANA_API_KEY"
  elif [[ -n "${LLM_API_KEY_FILE:-}" && -r "$LLM_API_KEY_FILE" ]]; then
    export LLM_API_KEY="$(tr -d '\r\n' < "$LLM_API_KEY_FILE")"
  elif [[ -n "${DIANA_API_KEY_FILE:-}" && -r "$DIANA_API_KEY_FILE" ]]; then
    export LLM_API_KEY="$(tr -d '\r\n' < "$DIANA_API_KEY_FILE")"
  fi
fi
export LLM_MODEL="${LLM_MODEL:-gpt-4o-mini}"
export LLM_USER_AGENT="${LLM_USER_AGENT:-diana-qq-bot}"

cd "$ROOT"
APP_EXECUTABLE="${DIANA_APP_EXECUTABLE:-$HOME/Applications/Diana QQ Bot.app/Contents/MacOS/diana-qq-bot-webui}"
if [[ -x "$APP_EXECUTABLE" ]]; then
  exec "$APP_EXECUTABLE"
fi
exec "$ROOT/dist/diana-qq-bot-webui"
